#!/usr/bin/env ruby

current_branch = `git rev-parse --abbrev-ref HEAD`
finish_name = current_branch.split('/').last
command = "git flow feature finish #{finish_name}"


puts `git checkout development`
puts `git pull`
puts `git checkout #{current_branch}`

puts `#{command}`
puts `git push origin`
