#!/usr/bin/env ruby

current_branch = `git rev-parse --abbrev-ref HEAD`

puts `git checkout servers/devtest`
puts `git pull`
unmerge = `git merge #{current_branch}`

if unmerged=~ /unmerged/i
  puts unmerged
else
  puts `git push`

  puts "Merged to servers/devtest"
  puts `git checkout #{current_branch}`

  puts "Deploy! cap devtest deploy"
  exec "cap devtest deploy && date"
end
