#!/usr/bin/env ruby

puts `git checkout development`

story_id = ARGV.shift.gsub('#','')

story_name = ARGV.join('_')

branch_name = "#{story_id}-#{story_name}"
command = "git flow feature start #{branch_name}"

puts `#{command}`
puts `git push origin`

puts `git branch --set-upstream-to=origin/feature/#{branch_name} feature/#{branch_name}`
