#!/usr/bin/env ruby

current_branch = `git rev-parse --abbrev-ref HEAD`

puts "Removing Devtest"
puts `git branch -D servers/devtest`
puts `git push origin :servers/devtest`

puts "Recreating Devtest"
puts `git checkout -b servers/devtest`
puts `git push origin`
puts `git branch --set-upstream-to=origin/servers/devtest servers/devtest`

puts `git pull`

puts "Mergin #{current_branch}"
puts `git merge #{current_branch}`

unmerged = `git status`

if unmerged =~ /unmerged/i
  puts unmerged
else
  puts "Pushing to Origin"
  puts `git push`

  puts "Merged to servers/devtest"
  puts `git checkout #{current_branch}`

  puts "Deploy! cap devtest deploy"
  exec "cap devtest deploy && date"
end
